# Use the RHEL official image as parent image
FROM redhat/ubi8:latest

# set shell
RUN export SHELL=/bin/bash

# Update
# RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN dnf upgrade -y
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm # dnf install epel-release
RUN dnf install -y bash-completion
RUN dnf install -y htop git gcc nano make which
RUN dnf install -y python38 python38-devel
RUN dnf install -y gcc-gfortran
RUN dnf install -y gcc-toolset-12
RUN scl enable gcc-toolset-12 bash

# RUN dnf install -y glpk #libglpk-dev
# RUN dnf install -y ncbi-blast+

# Install ZenglerLab coralme software stack
# general purpose
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib64/python3.8/site-packages

# coralme
RUN python3 -m pip install coralme

# jupyter and plot
RUN python3 -m pip install ipykernel
RUN python3 -m pip install matplotlib
RUN python3 -m pip install seaborn
RUN python3 -m pip install notebook

# Install jupyter notebook extensions (not working)
# RUN python3 -m pip install jupyter_nbextensions_configurator nbserverproxy

# Download the coralme tutorial
# RUN mkdir -p /opt/notebooks/coralme-tutorial
# WORKDIR /opt/notebooks/coralme-tutorial
# RUN git init
# RUN git remote add -f origin https://github.com/ZenglerLab/coralme
# RUN git config core.sparseCheckout true
# RUN echo "docs" >> .git/info/sparse-checkout
# RUN git pull origin master
# RUN mv docs/GettingStarted.ipynb .
# RUN mv docs/helper_files .
# RUN rm -rf docs .git

# Set the working directory
WORKDIR /opt

# Set jupyter configuration
RUN jupyter notebook --generate-config
# RUN wget https://raw.githubusercontent.com/glucksfall/zenglerlab/master/jupyter_notebook_config.json --directory-prefix=/root/.jupyter
COPY ./jupyter_notebook_config.json /root/.jupyter/jupyter_notebook_config.json

# Initiate jupyter server at runtime
CMD ["jupyter", "notebook", "--notebook-dir=/opt", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
