ME-Model-ID: EXAMPLE-BACILLUS-ME
amino_acid_trna_synthetase:
  ala__L_c: BSU27410-MONOMER
  arg__L_c: BSU37330-MONOMER
  asn__L_c: BSU22360-MONOMER
  asp__L_c: BSU27550-MONOMER
  cys__L_c: BSU00940-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: BSU00920-MONOMER
  gly_c: CPLX-tRNA-GLY-LIGASE
  his__L_c: BSU27560-MONOMER
  ile__L_c: BSU15430-MONOMER
  leu__L_c: BSU30320-MONOMER
  lys__L_c: BSU00820-MONOMER
  met__L_c: BSU00380-MONOMER
  phe__L_c: CPLX-tRNA-PHE-LIGASE
  pro__L_c: BSU16570-MONOMER
  ser__L_c: BSU00130-MONOMER
  thr__L_c: generic_thr_ligase
  trp__L_c: BSU11420-MONOMER
  tyr__L_c: generic_tyr_ligase
  val__L_c: BSU28090-MONOMER
braun's_lipoprotein: []
braun's_lipoproteins: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
complex_cofactors:
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  fes_chaperones: {}
  fes_transfers:
  - CPLX_dummy
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
default_sigma_factor: BSU25200-MONOMER
defer_to_rxn_matrix:
- BIOMASS_BS_10
- FMETTRS
- ATPM
df_TranscriptionalUnits: ./helper_files//building_data/TUs_from_biocyc.txt
df_gene_cplxs_mods_rxns: ./helper_files/building_data/OSM.xlsx
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
gam: 104.997414
genbank-path: ./helper_files//building_data/genome_modified.gb
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
growth_key: mu
lipid_modifications: []
lipoprotein_precursors: {}
locus_tag: old_locus_tag
log_directory: ./helper_files/
m-model-path: ./helper_files//building_data/m_model_modified.json
ngam: 9.0
other_lipids: CPLX_dummy
out_directory: ./helper_files/
peptide_release_factors:
  UAA: generic_RF
  UAG: CPLX_dummy
  UGA: CPLX_dummy
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
pg_pe_160: CPLX_dummy
rna_polymerases:
  RNAP_BSU00980MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU00980-MONOMER
  RNAP_BSU01730MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU01730-MONOMER
  RNAP_BSU04730MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU04730-MONOMER
  RNAP_BSU09520MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU09520-MONOMER
  RNAP_BSU12560MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU12560-MONOMER
  RNAP_BSU13450MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU13450-MONOMER
  RNAP_BSU14730MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU14730-MONOMER
  RNAP_BSU15320MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU15320-MONOMER
  RNAP_BSU15330MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU15330-MONOMER
  RNAP_BSU16470MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU16470-MONOMER
  RNAP_BSU23100MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU23100-MONOMER
  RNAP_BSU23450MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU23450-MONOMER
  RNAP_BSU25200MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU25200-MONOMER
  RNAP_BSU26840MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU26840-MONOMER
  RNAP_BSU27120MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU27120-MONOMER
  RNAP_BSU34200MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU34200-MONOMER
  RNAP_BSU38700MONOMER:
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU38700-MONOMER
selenocysteine_enzymes:
- CPLX_dummy
translocation_multipliers: {}
unmodeled_protein_fraction: 0.36
