ME-Model-ID: bsubtilis
amino_acid_trna_synthetase:
  ala__L_c: BSU27410-MONOMER_mod_zn2(4)
  arg__L_c: BSU37330-MONOMER_mod_mg2(1)
  asn__L_c: BSU22360-MONOMER
  asp__L_c: BSU27550-MONOMER
  cys__L_c: BSU00940-MONOMER_mod_zn2(1)
  gln__L_c: CPLX_dummy
  glu__L_c: BSU00920-MONOMER_mod_mg2(1)_mod_zn2(1)
  gly_c: CPLX8J2-12
  his__L_c: BSU27560-MONOMER_mod_mg2(4)
  ile__L_c: BSU15430-MONOMER_mod_zn2(2)
  leu__L_c: BSU30320-MONOMER
  lys__L_c: generic_LYSINEaaRS
  met__L_c: BSU00380-MONOMER_mod_zn2(2)
  phe__L_c: CPLX8J2-11_mod_mg2(1)
  pro__L_c: BSU16570-MONOMER
  ser__L_c: BSU00130-MONOMER_mod_mg2(1)
  thr__L_c: BSU37560-MONOMER_mod_zn2(1)
  trp__L_c: BSU11420-MONOMER_mod_mg2(1)
  tyr__L_c: BSU29670-MONOMER
  val__L_c: BSU28090-MONOMER_mod_mg2(1)
biocyc.RNAs: ./bsubtilis/inputs/RNAs.txt
biocyc.TUs: ./bsubtilis/inputs/TUs.txt
biocyc.genes: ./bsubtilis/inputs/genes.txt
biocyc.prots: ./bsubtilis/inputs/proteins.txt
biocyc.seqs: ./bsubtilis/inputs/sequences.fasta
braun's_lipoprotein: []
braun's_lipoproteins: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
complex_cofactors:
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  bmocogdp_chaperones: {}
  fes_chaperones: {}
  fes_transfers:
  - SufSU
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
default_sigma_factor: BSU25200-MONOMER
defer_to_rxn_matrix:
- ETOHt3
- FMETTRS
- ATPM
dev_reference: true
df_TranscriptionalUnits: ./bsubtilis/inputs/TUs_from_biocyc.txt
df_gene_cplxs_mods_rxns: ./bsubtilis/building_data/automated-org-with-refs.xlsx
df_matrix_stoichiometry: ./bsubtilis/inputs/reaction_matrix.txt
df_matrix_subrxn_stoich: ./bsubtilis/inputs/subreaction_matrix.txt
df_metadata_metabolites: ./bsubtilis/inputs/me_metabolites.txt
df_metadata_orphan_rxns: ./bsubtilis/inputs/orphan_and_spont_reactions.txt
flux_of_biomass_constituents:
  10fthf_c: -0.000367
  mql7_c: -0.000266
  nad_c: -0.016164
  nadp_c: -0.000934
  nadph_c: -0.000216
  peptido_BS_c: -0.101817
  ppi_c: -0.000918
flux_of_lipid_constituents:
  cdlp_BS_c: -5.0e-06
  d12dg_BS_c: -0.00011
  gtca1_45_BS_c: -0.003624
  gtca2_45_BS_c: -0.002347
  gtca3_45_BS_c: -0.001819
  lipo1_24_BS_c: -7.0e-06
  lipo2_24_BS_c: -6.0e-06
  lipo3_24_BS_c: -1.8e-05
  lipo4_24_BS_c: -1.5e-05
  lysylpgly_BS_c: -2.2e-05
  m12dg_BS_c: -8.6e-05
  pgly_BS_c: -0.000176
  psetha_BS_c: -0.00056
  t12dg_BS_c: -6.6e-05
  tcam_BS_c: -0.003112
gam: 105.053483
genbank-path: ./bsubtilis//building_data/genome_modified.gb
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
growth_key: mu
include_pseudo_genes: true
lipid_modifications: []
lipoprotein_precursors:
  MetQ: BSU32730
locus_tag: old_locus_tag
log_directory: ./bsubtilis/
m-model-path: ./bsubtilis//building_data/m_model_modified.json
ngam: 9
other_lipids:
- ''
out_directory: ./bsubtilis/
peptide_release_factors:
  UAA: generic_RF
  UAG: BSU37010-MONOMER
  UGA: BSU35290-MONOMER
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
pg_pe_160:
- BSU34990-MONOMER
- BSU15450-MONOMER
rna_polymerases:
  RNAP_BSU00980MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU00980-MONOMER
  RNAP_BSU01730MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU01730-MONOMER
  RNAP_BSU04730MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU04730-MONOMER
  RNAP_BSU09520MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU09520-MONOMER
  RNAP_BSU12560MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU12560-MONOMER
  RNAP_BSU13450MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU13450-MONOMER
  RNAP_BSU14730MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU14730-MONOMER
  RNAP_BSU15320MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU15320-MONOMER
  RNAP_BSU15330MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU15330-MONOMER
  RNAP_BSU16470MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU16470-MONOMER
  RNAP_BSU23100MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU23100-MONOMER
  RNAP_BSU23450MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU23450-MONOMER
  RNAP_BSU25200MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU25200-MONOMER
  RNAP_BSU26840MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU26840-MONOMER
  RNAP_BSU27120MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU27120-MONOMER
  RNAP_BSU34200MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU34200-MONOMER
  RNAP_BSU38700MONOMER:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: BSU38700-MONOMER
  RNAP_CPLX8J236:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-36
  RNAP_CPLX8J244:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-44
  RNAP_CPLX8J245:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-45
  RNAP_CPLX8J246:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-46
  RNAP_CPLX8J247:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-47
  RNAP_CPLX8J248:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-48
  RNAP_CPLX8J249:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-49
  RNAP_CPLX8J250:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-50
  RNAP_CPLX8J251:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-51
  RNAP_CPLX8J252:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-52
  RNAP_CPLX8J253:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-53
  RNAP_CPLX8J254:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-54
  RNAP_CPLX8J255:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-55
  RNAP_CPLX8J256:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-56
  RNAP_CPLX8J257:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-57
  RNAP_CPLX8J258:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-58
  RNAP_CPLX8J259:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-59
  RNAP_CPLX8J260:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-60
  RNAP_CPLX8J261:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: CPLX8J2-61
  RNAP_MONOMER8J253:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: MONOMER8J2-53
  RNAP_MONOMER8J254:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: MONOMER8J2-54
  RNAP_MONOMER8J26:
    polymerase: CPLX8J2-30_mod_zn2(1)_mod_mg2(2)
    sigma_factor: MONOMER8J2-6
run_bbh_blast: true
selenocysteine_enzymes:
- CPLX_dummy
translocation_multipliers:
  BSU41040-MONOMER:
    BSU36800: 2.0
trna_misacylation:
  Gln: Glu
unmodeled_protein_fraction: 0.36
